authapp/urls.py
from django.urls import path, include

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login_view, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('', include('django.contrib.auth.urls')),
    # path('edit/', authapp.edit, name='edit'),
    path('signup/', authapp.RegisterView.as_view(), name='register'),
    path('signup/traveler/', authapp.TravelerSignupView.as_view(), name='signup_traveler'),
    path('signup/instructor/', authapp.InstructorSignupView.as_view(), name='signup_instructor'),
    # path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

my_region/urls.py
from django.contrib import admin
from django.urls import path, include
import mainsite.views as main_views
import travelapp.views as travel_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.main, name='main'),
    path('travel/', include('travelapp.urls', namespace='travel')),
    path('user/', include('userapp.urls', namespace='user')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('social/', include('socialapp.urls', namespace='social')),
]

socialapp/urls.py
from django.urls import path

from socialapp import views as socialapp

app_name = 'socialapp'

urlpatterns = [
    path('trip_comment/create/<int:pk>', socialapp.TripCommentCreate.as_view(), name='trip_comment_create'),
]

travelapp/urls.py
import travelapp.views as travelapp
from django.urls import path

app_name = 'travelapp'

urlpatterns = [
    path('', travelapp.TripSelectorList.as_view(), name='trip_selector'),
    path('routes/', travelapp.RouteList.as_view(), name='route_list'),
    path('route/create/', travelapp.RouteCreateView.as_view(), name='route_create'),
    path('route/<int:pk>/', travelapp.RouteDetail.as_view(), name='route_read'),
    # path('route/update/<int:pk>/', travelapp.RouteUpdate.as_view(), name='route_update'),
    # path('route/delete/<int:pk>/', travelapp.RouteDelete.as_view(), name='route_delete'),
    path('trip/<int:pk>', travelapp.TripDetail.as_view(), name='trip_read'),
]

userapp/urls.py
import userapp.views as userapp
from django.urls import path

app_name = 'userapp'

urlpatterns = [
    path('instructors/', userapp.InstructorList.as_view(), name='instructor_list'),
    # path('create/', userapp..as_view(), name='user_create'),
    path('traveler_details/<int:pk>/', userapp.TravelerDetailView.as_view(), name='traveler_details'),
    path('instructor_details/<int:pk>/', userapp.InstructorDetailView.as_view(), name='instructor_details'),
    path('traveler_profile/', userapp.TravelerProfileView.as_view(), name='traveler_profile'),
    path('instructor_profile/', userapp.InstructorDetailView.as_view(), name='instructor_profile'),
]

authapp/models.py
from datetime import timedelta

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from ordersapp.models import OrderItem


class Gender(models.IntegerChoices):
    FEMALE = 1, _('Женский')
    MALE = 2, _('Мужской')


class AppUser(AbstractUser):
    avatar = models.ImageField(upload_to='static/user_pics', blank=True)
    date_of_birth = models.DateField(verbose_name='Дата рождения', default=now)
    activation_key = models.CharField(verbose_name='Ключ активации', max_length=128, blank=True)
    activation_key_expiry = models.DateTimeField(
        verbose_name='Крайний срок текущей активации',
        default=now() + timedelta(hours=24),
    )
    gender = models.IntegerField(verbose_name='Пол', blank=False, db_index=True, choices=Gender.choices)
    phone = models.CharField(verbose_name='Номер телефона', blank=True, max_length=20)
    email = models.EmailField(verbose_name='Адрес Email', unique=True)
    is_instructor = models.BooleanField(default=False, null=False, db_index=True)
    is_traveler = models.BooleanField(default=False, null=False, db_index=True)
    # phone_number

    def is_key_expired(self):
        if now() <= self.activation_key_expiry:
            return False
        else:
            return True


class Traveler(models.Model):
    user = models.OneToOneField(AppUser, unique=True, db_index=True, null=False, on_delete=models.CASCADE)
    about = models.TextField(verbose_name='О себе', blank=True)
    home_region = models.CharField(verbose_name='Место проживания', max_length=100)
    following = models.ManyToManyField('Instructor', verbose_name='Подписки', blank=True, related_name='followers')
    trips_completed = models.ManyToManyField('travelapp.Trip', verbose_name='Походы', related_name='participants')

    def __str__(self):
        return f'{self.user.get_full_name()} ({self.home_region})'

    # todo: implement a model manager
    def get_planned_trips(self):
        return OrderItem.objects.filter(trip__starts_at__gte=now(), traveler=self)

    def get_active_trips(self):
        return OrderItem.objects.filter(trip__starts_at__lte=now(),
                                        trip__ends_at__gte=now(),
                                        traveler=self,
                                        )

    def get_finished_trips(self):
        return OrderItem.objects.filter(trip__ends_at__lte=now(), traveler=self)


class Instructor(models.Model):
    user = models.OneToOneField(AppUser, unique=True, db_index=True, null=True, on_delete=models.CASCADE)
    about = models.TextField(verbose_name='О себе', blank=True)
    home_region = models.CharField(verbose_name='Место проживания', max_length=100, blank=True)
    routes_run = models.IntegerField(verbose_name='Пройдено маршрутов', default=0)
    is_active = models.BooleanField(verbose_name='Инструктор доступен для маршрута', default=True)
    # subscribers = models.ManyToManyField(Traveler, verbose_name='Подписчики', blank=True, related_name='subscribed_to')

    def __str__(self):
        return f'{self.user.get_full_name()} ({self.home_region})'

userapp/models.py
from django.db import models


class Traveler(models.Model):
    name = models.CharField(verbose_name='ФИО пользователя', max_length=200)
    about = models.TextField(verbose_name='О себе', blank=True)
    home_region = models.CharField(verbose_name='Место проживания', max_length=100)
    following = models.ManyToManyField('Instructor', verbose_name='Подписки', blank=True, related_name='followers')
    trips_completed = models.ManyToManyField('travelapp.Trip', verbose_name='Походы', related_name='participants')

    def __str__(self):
        return f'{self.name} ({self.home_region})'


class Instructor(models.Model):
    name = models.CharField(verbose_name='ФИО инструктора', max_length=200)
    about = models.TextField(verbose_name='О себе', blank=True)
    home_region = models.CharField(verbose_name='Место проживания', max_length=100, blank=True)
    routes_run = models.IntegerField(verbose_name='Пройдено маршрутов', default=0)
    is_active = models.BooleanField(verbose_name='Инструктор доступен для маршрута', default=True)
    # subscribers = models.ManyToManyField(Traveler, verbose_name='Подписчики', blank=True, related_name='subscribed_to')

    def __str__(self):
        return f'{self.name} ({self.home_region})'

userapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView

from authapp.decorators import traveler_only
from authapp.models import Instructor, Traveler


class InstructorList(ListView):
    model = Instructor


class InstructorDetail(DetailView):
    model = Instructor


class TravelerDetailView(DetailView):
    model = Traveler
    template_name = 'userapp/traveler_detail.html'


@method_decorator([login_required, traveler_only], name='dispatch')
class TravelerProfileView(DetailView):
    model = Traveler
    template_name = 'userapp/traveler_profile.html'
    context_object_name = 'traveler'

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, pk=self.request.user.traveler.pk)


class InstructorDetailView(DetailView):
    model = Instructor
    template_name = 'userapp/instructor_detail.html'

userapp/templates/userapp/instructor_detail.html
{% extends 'mainsite/base.html' %}

{% block content %}
    <p>{{ object.user.get_full_name }}</p>
    <p>{{ object.user.avatar }}</p>
    <p>{{ object.user.date_of_birth }}</p>
    <p>{{ object.about }}</p>
    <p>{{ object.home_region }}</p>
    <a href="{% url 'travelapp:route_create' %}" class="my-3 btn btn-info">Создать маршрут</a>
    <a href="#" class="my-3 btn btn-outline-secondary">Создать поход</a>
    <h3>Созданные походы</h3>
    {% for order in object.created_trips.all %}
        <div class="row justify-content-center">
            <div class="col-2 border">{{ order.trip.starts_at|date:"d M Y" }} {{order.trip.starts_at|time:"H:i"}}</div>
            <div class="col-4 border">{{ order.trip.route.name }}</div>
            <div class="col-2 border">{{ order.trip.get_cost }} р.</div>
            <div class="col-1 border">{{ order.trip.subbed }}/{{ order.trip.max_group_size }}</div>
        </div>
    {% empty %}
      <p>У вас не запланировано ни одного похода.</p>
    {% endfor %}
{% endblock %}

userapp/templates/userapp/traveler_detail.html
{% extends 'mainsite/base.html' %}

{% block content %}
    <div class="h4 col-12 text-center border rounded">Данные о пользователе {{ object.username }}</div>
        <div class="row my-4">
            <div class="col-3 route-image">
                <img class="rounded-circle img-fluid img-thumbnail" src="/{{ object.user.avatar }}" />
            </div>
            <div class="col-8 text-center">
                <div class="row">
                    <div class="col-12 border rounded m-1">{{ object.user.get_full_name }}</div>
                </div>
                <div class="row">
                    <div class="col border rounded m-1">Пол: {{ object.user.get_gender_display }}</div>
                    <div class="col border rounded m-1">Дата рождения: {{ object.user.date_of_birth }}</div>
                </div>
                <div class="row">
                    <div class="col border rounded m-1">{{ object.about }}</div>
                    <div class="col border rounded m-1">{{ object.experience_desc }}</div>
                </div>
            </div>
        </div>
    <div class="h5 col-12 text-center border rounded my-3">Пройденные маршруты</div>
{% endblock %}

userapp/templates/userapp/traveler_profile.html
{% extends 'mainsite/base.html' %}

{% block content %}
    <div class="h4 col-12 text-center border rounded">Личный кабинет пользователя</div>
        <div class="row my-4">
            <div class="col-3 route-image">
                <img class="rounded-circle img-fluid img-thumbnail" src="/{{ traveler.user.avatar }}" />
            </div>
            <div class="col-8 text-center">
                <div class="row">
                    <div class="col-12 border rounded m-1">{{ traveler.user.get_full_name }}</div>
                </div>
                <div class="row">
                    <div class="col border rounded m-1">Пол: {{ traveler.user.get_gender_display }}</div>
                    <div class="col border rounded m-1">Дата рождения: {{ traveler.user.date_of_birth }}</div>
                </div>
                <div class="row">
                    <div class="col border rounded m-1">{{ traveler.about }}</div>
                    <div class="col border rounded m-1">{{ traveler.experience_desc }}</div>
                </div>
            </div>
        </div>
    <div class="h4 col-12 text-center border rounded">Мои маршруты</div>
    <div class="h5 col-12 text-center border rounded">Избранные маршруты</div>
    <div class="h5 col-12 text-center border rounded my-3">Запланированные походы</div>
    {% for order in traveler.get_planned_trips.all %}
        {% if forloop.first %}
        <div class="row justify-content-center font-weight-bold">
            <div class="col-2 border">Время похода</div>
            <div class="col-3 border">Наименование</div>
            <div class="col-2 border">Стоимость</div>
            <div class="col-2 border">С вами (дет/взр)</div>
            <div class="col-1 border">Занято мест</div>
        </div>
        {% endif %}
        <div class="row justify-content-center ">
            <div class="col-2 border">{{ order.trip.starts_at|date:"d M Y" }} {{order.trip.starts_at|time:"H:i"}}</div>
            <div class="col-3 border">{{ order.trip.route.name }}</div>
            <div class="col-2 border">{{ order.trip.get_cost }} р.</div>
            <div class="col-2 border">{{ order.kids_amount }}/{{ order.adults_amount }}</div>
            <div class="col-1 border">{{ order.trip.subbed }}/{{ order.trip.max_group_size }}</div>
        </div>
    {% empty %}
      <p>У вас не запланировано ни одного похода.</p>
    {% endfor %}
    <div class="h5 col-12 text-center border rounded my-3">Пройденные походы</div>
    {% for order in traveler.get_finished_trips.all %}
        {% if forloop.first %}
        <div class="row justify-content-center font-weight-bold">
            <div class="col-2 border">Время похода</div>
            <div class="col-3 border">Наименование</div>
            <div class="col-2 border">Стоимость</div>
            <div class="col-2 border">С вами (дет/взр)</div>
            <div class="col-1 border">Оставить оценку</div>
        </div>
        {% endif %}
        <div class="row justify-content-center ">
            <div class="col-2 border">{{ order.trip.starts_at|date:"d M Y" }} {{order.trip.starts_at|time:"H:i"}}</div>
            <div class="col-3 border">{{ order.trip.route.name }}</div>
            <div class="col-2 border">{{ order.trip.get_cost }} р.</div>
            <div class="col-2 border">{{ order.kids_amount }}/{{ order.adults_amount }}</div>
            <div class="col-1 border"><a href="{% url 'socialapp:trip_comment_create' order.trip.pk %}" class="btn btn-sm btn-info">Оценить</a></div>
        </div>
    {% empty %}
      <p>Вы пока что не прошли ни одного похода.</p>
    {% endfor %}
{% endblock %}