authapp/urls.py
from django.urls import path, include

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login_view, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('', include('django.contrib.auth.urls')),
    # path('edit/', authapp.edit, name='edit'),
    path('signup/', authapp.RegisterView.as_view(), name='register'),
    path('signup/traveler/', authapp.TravelerSignupView.as_view(), name='signup_traveler'),
    path('signup/instructor/', authapp.InstructorSignupView.as_view(), name='signup_instructor'),
    # path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

my_region/urls.py
from django.contrib import admin
from django.urls import path, include
import mainsite.views as main_views
import travelapp.views as travel_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.main, name='main'),
    path('travel/', include('travelapp.urls', namespace='travel')),
    path('user/', include('userapp.urls', namespace='user')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('social/', include('socialapp.urls', namespace='social')),
]

authapp/models.py
from datetime import timedelta

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from ordersapp.models import OrderItem


class Gender(models.IntegerChoices):
    FEMALE = 1, _('Женский')
    MALE = 2, _('Мужской')


class AppUser(AbstractUser):
    avatar = models.ImageField(upload_to='static/user_pics', blank=True)
    date_of_birth = models.DateField(verbose_name='Дата рождения', default=now)
    activation_key = models.CharField(verbose_name='Ключ активации', max_length=128, blank=True)
    activation_key_expiry = models.DateTimeField(
        verbose_name='Крайний срок текущей активации',
        default=now() + timedelta(hours=24),
    )
    gender = models.IntegerField(verbose_name='Пол', blank=False, db_index=True, choices=Gender.choices)
    phone = models.CharField(verbose_name='Номер телефона', blank=True, max_length=20)
    email = models.EmailField(verbose_name='Адрес Email', unique=True)
    is_instructor = models.BooleanField(default=False, null=False, db_index=True)
    is_traveler = models.BooleanField(default=False, null=False, db_index=True)
    # phone_number

    def is_key_expired(self):
        if now() <= self.activation_key_expiry:
            return False
        else:
            return True


class Traveler(models.Model):
    user = models.OneToOneField(AppUser, unique=True, db_index=True, null=False, on_delete=models.CASCADE)
    about = models.TextField(verbose_name='О себе', blank=True)
    home_region = models.CharField(verbose_name='Место проживания', max_length=100)
    following = models.ManyToManyField('Instructor', verbose_name='Подписки', blank=True, related_name='followers')
    trips_completed = models.ManyToManyField('travelapp.Trip', verbose_name='Походы', related_name='participants')

    def __str__(self):
        return f'{self.user.get_full_name()} ({self.home_region})'

    # todo: implement a model manager
    def get_planned_trips(self):
        return OrderItem.objects.filter(trip__starts_at__gte=now(), traveler=self)

    def get_active_trips(self):
        return OrderItem.objects.filter(trip__starts_at__lte=now(),
                                        trip__ends_at__gte=now(),
                                        traveler=self,
                                        )

    def get_finished_trips(self):
        return OrderItem.objects.filter(trip__ends_at__lte=now(), traveler=self)


class Instructor(models.Model):
    user = models.OneToOneField(AppUser, unique=True, db_index=True, null=True, on_delete=models.CASCADE)
    about = models.TextField(verbose_name='О себе', blank=True)
    home_region = models.CharField(verbose_name='Место проживания', max_length=100, blank=True)
    routes_run = models.IntegerField(verbose_name='Пройдено маршрутов', default=0)
    is_active = models.BooleanField(verbose_name='Инструктор доступен для маршрута', default=True)
    # subscribers = models.ManyToManyField(Traveler, verbose_name='Подписчики', blank=True, related_name='subscribed_to')

    def __str__(self):
        return f'{self.user.get_full_name()} ({self.home_region})'

authapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.db import transaction
from django.utils.timezone import now

from authapp.models import AppUser, Traveler, Instructor


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = AppUser
        fields = ('username', 'password')


class SignupForm(UserCreationForm):
    about = forms.CharField(required=True)
    home_region = forms.CharField()

    class Meta(UserCreationForm.Meta):
        model = AppUser
        fields = ['username', 'email', 'phone', 'first_name', 'last_name', 'gender', 'date_of_birth', 'password1', 'password2', 'avatar']

    def clean_date_of_birth(self):
        dob = self.cleaned_data['date_of_birth']
        delta = now().year - dob.year - ((now().month, now().day) < (dob.month, dob.day))
        if delta < 18:
            raise forms.ValidationError("Вам должно быть более 18 лет!")

        return dob

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user_type = self.data.get('user_type', None)
        if user_type == 'traveler':
            user.is_traveler = True
            profile_maker = Traveler
        elif user_type == 'instructor':
            user.is_instructor = True
            profile_maker = Instructor

        user.save()
        profile = profile_maker.objects.create(user=user)

        # print(self.cleaned_data)
        profile.about = self.cleaned_data.get('about')
        profile.home_region = self.cleaned_data.get('home_region')
        profile.save()
        return user

authapp/views.py
from django.contrib import auth
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, TemplateView

from authapp.forms import SignupForm, UserLoginForm
from authapp.models import AppUser


def login_view(request):
    title = 'login'

    login_form = UserLoginForm(data=request.POST or None)

    next = request.GET['next'] if 'next' in request.GET.keys() else ''

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys() and request.POST['next']:
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse_lazy('main'))

    content = {
        'title': title,
        'login_form': login_form,
        'next': next,
    }
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


class RegisterView(TemplateView):
    template_name = 'authapp/register.html'


class TravelerSignupView(CreateView):
    model = AppUser
    form_class = SignupForm
    template_name = 'authapp/signup.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'traveler'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('main')


class InstructorSignupView(CreateView):
    model = AppUser
    form_class = SignupForm
    template_name = 'authapp/signup.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'instructor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('main')

authapp/templates/authapp/login.html
{% extends 'mainsite/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% if login_form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      {% for error in login_form.non_field_errors %}
        <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
      {% endfor %}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endif %}
  <div class="row">
    <div class="col-lg-4 col-md-6 col-sm-8 col-12">
      <h2>Войти</h2>
      <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {{ login_form.username|as_crispy_field }}
        {{ login_form.password|as_crispy_field }}
        <button type="submit" class="btn btn-primary">Войти</button>
        <a href="{% url 'authapp:register' %}" class="btn btn-info">Регистрация</a>
      </form>
    </div>
  </div>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'mainsite/base.html' %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-sm-10 col-12">
      <h2>Регистрация аккаунта</h2>
      <p class="lead">Выберите тип пользователя:</p>
      <a href="{% url 'authapp:signup_traveler' %}" class="btn btn-info btn-lg" role="button">Путешественник</a>
      <a href="{% url 'authapp:signup_instructor' %}" class="btn btn-success btn-lg" role="button">Инструктор</a>
    </div>
  </div>
{% endblock %}

authapp/templates/authapp/signup.html
{% extends 'mainsite/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-sm-10 col-12">
      <h2>Sign up as a {{ user_type }}</h2>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <input type="hidden" name="user_type" value="{{ user_type }}">
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Sign up</button>
      </form>
    </div>
  </div>
{% endblock %}