authapp/urls.py
from django.urls import path, include

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login_view, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('', include('django.contrib.auth.urls')),
    # path('edit/', authapp.edit, name='edit'),
    path('signup/', authapp.RegisterView.as_view(), name='register'),
    path('signup/traveler/', authapp.TravelerSignupView.as_view(), name='signup_traveler'),
    path('signup/instructor/', authapp.InstructorSignupView.as_view(), name='signup_instructor'),
    # path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

my_region/urls.py
from django.contrib import admin
from django.urls import path, include
import mainsite.views as main_views
import travelapp.views as travel_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.main, name='main'),
    path('travel/', include('travelapp.urls', namespace='travel')),
    path('user/', include('userapp.urls', namespace='user')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('social/', include('socialapp.urls', namespace='social')),
]

travelapp/urls.py
import travelapp.views as travelapp
from django.urls import path

app_name = 'travelapp'

urlpatterns = [
    path('', travelapp.TripSelectorList.as_view(), name='trip_selector'),
    path('routes/', travelapp.RouteList.as_view(), name='route_list'),
    path('route/create/', travelapp.RouteCreateView.as_view(), name='route_create'),
    path('route/<int:pk>/', travelapp.RouteDetail.as_view(), name='route_read'),
    # path('route/update/<int:pk>/', travelapp.RouteUpdate.as_view(), name='route_update'),
    # path('route/delete/<int:pk>/', travelapp.RouteDelete.as_view(), name='route_delete'),
    path('trip/<int:pk>', travelapp.TripDetail.as_view(), name='trip_read'),
]

userapp/urls.py
import userapp.views as userapp
from django.urls import path

app_name = 'userapp'

urlpatterns = [
    path('instructors/', userapp.InstructorList.as_view(), name='instructor_list'),
    # path('create/', userapp..as_view(), name='user_create'),
    path('traveler_details/<int:pk>/', userapp.TravelerDetailView.as_view(), name='traveler_details'),
    path('instructor_details/<int:pk>/', userapp.InstructorDetailView.as_view(), name='instructor_details'),
    path('traveler_profile/', userapp.TravelerProfileView.as_view(), name='traveler_profile'),
    path('instructor_profile/', userapp.InstructorDetailView.as_view(), name='instructor_profile'),
]

mainsite/models.py
from django.db import models

# Create your models here.

mainsite/views.py
from django.shortcuts import render

# Create your views here.


def main(request):
    title = 'Travel Freely!'

    content = {
        'title': title,
    }

    return render(request, 'mainsite/index.html', context=content)

mainsite/templates/mainsite/includes/inc_menu.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark my-3">
    <a href="#" class="navbar-brand">Мой Край</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbarCollapse" style="">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main' %}">Главная <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'travelapp:trip_selector' %}">Выбрать поход</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'travelapp:route_list' %}">Маршруты</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Обучение</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Контакты</a>
        </li>
    </ul>
    <ul class="navbar-nav mt-2 mt-md-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="
            {% if user.is_traveler == True %}
                {% url 'userapp:traveler_profile' %}
            {% else %}
                {% url 'userapp:instructor_profile' %}
            {% endif %}">{{ user.first_name|default:'User' }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'auth:logout' %}">Выйти</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authapp:login' %}">Вход</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authapp:register' %}">Регистрация</a>
        </li>
        {% endif %}
    </ul>
    </div>
</nav>