authapp/urls.py
from django.urls import path, include

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login_view, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('', include('django.contrib.auth.urls')),
    # path('edit/', authapp.edit, name='edit'),
    path('signup/', authapp.RegisterView.as_view(), name='register'),
    path('signup/traveler/', authapp.TravelerSignupView.as_view(), name='signup_traveler'),
    path('signup/instructor/', authapp.InstructorSignupView.as_view(), name='signup_instructor'),
    # path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

my_region/urls.py
from django.contrib import admin
from django.urls import path, include
import mainsite.views as main_views
import travelapp.views as travel_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.main, name='main'),
    path('travel/', include('travelapp.urls', namespace='travel')),
    path('user/', include('userapp.urls', namespace='user')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('social/', include('socialapp.urls', namespace='social')),
]

ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import path

app_name = 'ordersapp'

urlpatterns = [
    # path('', travelapp.RouteList.as_view(), name='route_list'),
    path('create/<int:pk>', ordersapp.OrderCreate.as_view(), name='create_order'),
    # path('route/<int:pk>/', travelapp.RouteDetail.as_view(), name='route_read'),
    # path('route/update/<int:pk>/', travelapp.RouteUpdate.as_view(), name='route_update'),
    # path('route/delete/<int:pk>/', travelapp.RouteDelete.as_view(), name='route_delete'),
    # path('trip/<int:pk>', travelapp.TripDetail.as_view(), name='trip_read'),
]

socialapp/urls.py
from django.urls import path

from socialapp import views as socialapp

app_name = 'socialapp'

urlpatterns = [
    path('trip_comment/create/<int:pk>', socialapp.TripCommentCreate.as_view(), name='trip_comment_create'),
]

travelapp/urls.py
import travelapp.views as travelapp
from django.urls import path

app_name = 'travelapp'

urlpatterns = [
    path('', travelapp.TripSelectorList.as_view(), name='trip_selector'),
    path('routes/', travelapp.RouteList.as_view(), name='route_list'),
    path('route/create/', travelapp.RouteCreateView.as_view(), name='route_create'),
    path('route/<int:pk>/', travelapp.RouteDetail.as_view(), name='route_read'),
    # path('route/update/<int:pk>/', travelapp.RouteUpdate.as_view(), name='route_update'),
    # path('route/delete/<int:pk>/', travelapp.RouteDelete.as_view(), name='route_delete'),
    path('trip/<int:pk>', travelapp.TripDetail.as_view(), name='trip_read'),
]

userapp/urls.py
import userapp.views as userapp
from django.urls import path

app_name = 'userapp'

urlpatterns = [
    path('instructors/', userapp.InstructorList.as_view(), name='instructor_list'),
    # path('create/', userapp..as_view(), name='user_create'),
    path('traveler_details/<int:pk>/', userapp.TravelerDetailView.as_view(), name='traveler_details'),
    path('instructor_details/<int:pk>/', userapp.InstructorDetailView.as_view(), name='instructor_details'),
    path('traveler_profile/', userapp.TravelerProfileView.as_view(), name='traveler_profile'),
    path('instructor_profile/', userapp.InstructorDetailView.as_view(), name='instructor_profile'),
]

travelapp/models.py
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from djmoney.models.fields import MoneyField
# from authapp.models import Instructor
from socialapp.models import TripComment


class RouteType(models.IntegerChoices):
    ON_FOOT = 1, _('Пеший')
    ON_BIKE = 2, _('Велосипедный')
    ON_BOAT = 3, _('Водный')


class RouteLevel(models.IntegerChoices):
    EASY = 1, _('Простой')
    ADVANCED = 2, _('Продвинутый')
    HARD = 3, _('Сложный')


# todo this is actually bad
class TripFilterQuerySet(models.QuerySet):
    def get_filtered(self, **kwargs):
        # todo: fix double query
        qs = self.filter(
            route__in=Route.objects.search(**kwargs),
            starts_at__gte=now(),
        )
        if kwargs.get('date_from', ''):
            qs = qs.filter(starts_at__gte=kwargs['date_from'])
        if kwargs.get('date_to', ''):
            qs = qs.filter(ends_at__lte=kwargs['date_to'])
        if kwargs.get('price_from', ''):
            qs = qs.filter(price__gte=int(kwargs['price_from']))
        if kwargs.get('price_to', ''):
            qs = qs.filter(price__lte=int(kwargs['price_to']))

        return qs


class RouteFilterQuerySet(models.QuerySet):
    def search(self, *args, **kwargs):
        qs = self.filter(is_active=True, is_checked=True)
        if kwargs.get('region', ''):
            qs = qs.filter(location=kwargs['region'])
        elif kwargs.get('district', ''):
            qs = qs.filter(location__district=kwargs['district'])
        if kwargs.get('type', ''):
            qs = qs.filter(type=kwargs['type'])
        if kwargs.get('level', ''):
            qs = qs.filter(complexity=kwargs['level'])

        return qs


class Route(models.Model):
    objects = RouteFilterQuerySet.as_manager()

    name = models.CharField(verbose_name='Название маршрута', max_length=100, unique=True)
    type = models.IntegerField(verbose_name='Тип',
                               choices=RouteType.choices,
                               default=RouteType.ON_FOOT,
                               db_index=True)
    base_price = models.DecimalField(verbose_name='Ориентировочная стоимость прохождения маршрута',
                                     max_digits=8,
                                     decimal_places=2,
                                     default=0)
    short_desc = models.TextField(verbose_name='Краткое описание')
    long_desc = models.TextField(verbose_name='Полное описание')
    # location = models.CharField(verbose_name='Местоположение', max_length=200, db_index=True)
    location = models.ForeignKey('travelapp.Region',
                                 verbose_name='Местоположение',
                                 db_index=True,
                                 null=True,
                                 on_delete=models.SET_NULL)
    duration = models.IntegerField(verbose_name='Продолжительность', db_index=True)
    length = models.FloatField(verbose_name='Длина', db_index=True)
    complexity = models.IntegerField(verbose_name='Сложность',
                                     choices=RouteLevel.choices,
                                     default=RouteLevel.EASY,
                                     db_index=True)
    added_at = models.DateTimeField(verbose_name='Время создания маршрута', auto_now_add=True)
    featured_photo = models.ImageField(upload_to='static/img', verbose_name='Фото для оформления маршрута', blank=True)
    is_active = models.BooleanField(verbose_name='Маршрут доступен для проведения', default=True, db_index=True, blank=False)
    is_checked = models.BooleanField(verbose_name='Модерация проведена', default=False, db_index=True, blank=False)
    instructor = models.ForeignKey('authapp.Instructor',
                                   related_name='routes',
                                   on_delete=models.SET_NULL,  # todo ?
                                   null=True,
                                   db_index=True)
    # height_difference
    # times_run
    # comments

    def get_planned_trips(self):
        return Trip.objects.filter(route=self, starts_at__gte=now())

    def get_active_trips(self):
        return Trip.objects.filter(route=self,
                                   starts_at__lte=now(),
                                   ends_at__gte=now(),
                                   )

    def get_finished_trips(self):
        return Trip.objects.filter(route=self, ends_at__lte=now())

    def get_route_comments(self):
        return TripComment.objects.filter(trip__route=self)

    @property
    def is_usable(self):
        return self.is_checked and self.is_active

    def __str__(self):
        return f'Маршрут "{self.name}"\n{self.location} ({self.type}, {self.length:.1f}км, {self.duration}ч)\n' \
               f'Сложность: {self.complexity}'


class RoutePhoto(models.Model):
    image = models.ImageField(upload_to='static/route_photos')
    added_at = models.DateTimeField(verbose_name='Время добавления', auto_now_add=True)
    route = models.ForeignKey(Route, related_name='photos', on_delete=models.CASCADE)


class Trip(models.Model):
    objects = TripFilterQuerySet.as_manager()
    route = models.ForeignKey('Route',
                              related_name='trips',
                              on_delete=models.CASCADE)
    price = models.DecimalField(verbose_name='Стоимость прохождения маршрута',
                                max_digits=8,
                                decimal_places=2,)
    announced_at = models.DateTimeField(verbose_name='Время объявления похода', auto_now_add=True)
    starts_at = models.DateTimeField(verbose_name='Время начала похода', blank=False, db_index=True)
    ends_at = models.DateTimeField(verbose_name='Время окончания похода', blank=False, db_index=True)
    instructor = models.ForeignKey('authapp.Instructor',
                                   related_name='trips',
                                   on_delete=models.CASCADE)
    kids = models.IntegerField(verbose_name='Детей в группе', default=0)
    adults = models.IntegerField(verbose_name='Взрослых в группе', default=0)
    # subbed = models.IntegerField(verbose_name='Мест занято', default=0)
    max_group_size = models.IntegerField(verbose_name='Количество мест', null=True)

    @property
    def subbed(self):
        return self.kids + self.adults
    #
    # @property
    # def ends_at(self):
    #     return self.starts_at + timedelta(days=self.route.duration)

    def get_cost(self):
        options_cost = 0
        for option in self.options.all():
            options_cost += option.price
        return self.price + options_cost

    def __str__(self):
        return f'Поход по маршруту "{self.route.name}" ({self.starts_at})'


class Options(models.IntegerChoices):
    INSURANCE = 1, _('Страховка')
    RENT = 2, _('Аренда инвентаря')
    FOOD = 3, _('Питание')
    LIVING_EXPENCES = 4, _('Проживание')
    TRANSIT = 5, _('Проезд до места')


class TripOptionAvailable(models.Model):
    trip = models.ManyToManyField('Trip',
                                  related_name='options',)
    name = models.IntegerField(verbose_name='Наименование опции',
                               choices=Options.choices,
                               )
    price = models.DecimalField(verbose_name='Стоимость опции',
                                max_digits=7,
                                decimal_places=2,
                                default=0)

    def __str__(self):
        return f'{self.get_name_display()}: {self.price} р.'


class District(models.Model):
    name = models.CharField(verbose_name='Наименование', max_length=50, blank=False, db_index=True)

    def __str__(self):
        return f'{self.name}'


class Region(models.Model):
    name = models.CharField(verbose_name='Наименование', max_length=50, blank=False, db_index=True)
    district = models.ForeignKey(District, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} ({self.district.name})'

travelapp/forms.py
from django import forms
from django.forms import SelectDateWidget

from .models import RouteType, RouteLevel, Route, District, Region


class RouteFilterForm(forms.Form):
    # name = forms.CharField(label='Название', max_length=100, required=False)
    # todo
    district = forms.ModelChoiceField(queryset=District.objects.all(),
                                      label='Округ',
                                      required=False,
                                      empty_label='Округ'
                                      )
    region = forms.ModelChoiceField(queryset=Region.objects.all(),
                                    label='Регион',
                                    empty_label='Регион',
                                    required=False)
    type = forms.ChoiceField(
        label='Тип маршрута',
        choices=[('', 'Тип маршрута')] + [(x, x.label) for x in RouteType],
        required=False,
    )
    level = forms.ChoiceField(
        label='Сложность',
        choices=[('', 'Сложность')] + [(x, x.label) for x in RouteLevel],
        required=False,
    )
    date_from = forms.DateField(label='Дата начала', required=False,
                                widget=SelectDateWidget())
    date_to = forms.DateField(label='Дата окончания', required=False,
                              widget=SelectDateWidget())
    price_from = forms.DecimalField(label='Цена от', required=False)
    price_to = forms.DecimalField(label='Цена до', required=False)


class RouteCreateForm(forms.ModelForm):
    class Meta:
        model = Route
        fields = ['name', 'type', 'base_price', 'short_desc', 'long_desc', 'location',
                  'duration', 'length', 'complexity', 'featured_photo']


class FullRouteCreateForm(RouteCreateForm):
    photos = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta(RouteCreateForm.Meta):
        fields = RouteCreateForm.Meta.fields + ['photos', ]

travelapp/views.py
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView

from travelapp.models import Route, Trip, RoutePhoto
from .forms import RouteFilterForm, FullRouteCreateForm


class RouteList(ListView):
    model = Route

    def get_context_data(self, **kwargs):
        data = super(RouteList, self).get_context_data(**kwargs)
        form = RouteFilterForm()
        data['form'] = form
        data['title'] = 'Список маршрутов'

        return data

    def get_queryset(self):
        if self.request.GET.items():
            form = RouteFilterForm(self.request.GET)
            if form.is_valid():
                return Route.objects.search(**form.cleaned_data)
        return Route.objects.filter(is_usable=True)


class TripSelectorList(ListView):
    model = Trip
    template_name = 'travelapp/trip_selector.html'
    context_object_name = 'trip_list'

    def get_context_data(self, **kwargs):
        data = super(TripSelectorList, self).get_context_data(**kwargs)
        form = RouteFilterForm()
        data['title'] = 'Выбрать поход'
        data['form'] = form
        data['route_list'] = Route.objects.all()[:6]

        return data

    def get_queryset(self):
        if self.request.GET.items():
            form = RouteFilterForm(self.request.GET)
            if form.is_valid():
                return Trip.objects.get_filtered(**form.cleaned_data)


class RouteDetail(DetailView):
    model = Route


class RouteCreateView(CreateView):
    model = Route
    form_class = FullRouteCreateForm
    success_url = reverse_lazy('travelapp:route_list')

    def form_valid(self, form):
        files = self.request.FILES.getlist('photos')
        form.instance.instructor = self.request.user.instructor
        form.cleaned_data.pop('photos')
        with transaction.atomic():
            result = super(RouteCreateView, self).form_valid(form)
            for photo in files:
                RoutePhoto.objects.create(image=photo, route=form.instance)

        return result


class TripDetail(DetailView):
    model = Trip

userapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView

from authapp.decorators import traveler_only
from authapp.models import Instructor, Traveler


class InstructorList(ListView):
    model = Instructor


class InstructorDetail(DetailView):
    model = Instructor


class TravelerDetailView(DetailView):
    model = Traveler
    template_name = 'userapp/traveler_detail.html'


@method_decorator([login_required, traveler_only], name='dispatch')
class TravelerProfileView(DetailView):
    model = Traveler
    template_name = 'userapp/traveler_profile.html'
    context_object_name = 'traveler'

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, pk=self.request.user.traveler.pk)


class InstructorDetailView(DetailView):
    model = Instructor
    template_name = 'userapp/instructor_detail.html'

travelapp/templates/travelapp/instructor_list.html
{% extends 'mainsite/base.html' %}
{% block content %}
<main role="main" class="container">
  <div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-4 mb-4 font-italic border-bottom">Список инструкторов</h3>
        {% for instructor in object_list %}
            {% if instructor.is_active %}
              <div class="blog-post">
                <h2 class="blog-post-title">{{ instructor.name }}</h2>

                <p>Место: {{ instructor.home_region }}</p>
                <hr>
                <p>{{ instructor.about }}</p>
                <hr>
                <p>Проведено маршрутов: {{ instructor.routes_run }}</p>
                <p>Подписчиков: {{ instructor.subscribers.count }}</p>

              </div><!-- /.blog-post -->
            {% endif %}
        {% endfor %}

      <nav class="blog-pagination">
        <a class="btn btn-outline-primary" href="#">Older</a>
        <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Newer</a>
      </nav>

    </div><!-- /.blog-main -->

    <aside class="col-md-4 blog-sidebar">
      <div class="p-4 mb-3 bg-light rounded">
        <h4 class="font-italic">About</h4>
        <p class="mb-0">Saw you downtown singing the Blues. Watch you circle the drain. Why don't you let me stop by? Heavy is the head that <em>wears the crown</em>. Yes, we make angels cry, raining down on earth from up above.</p>
      </div>

      <div class="p-4">
        <h4 class="font-italic">Archives</h4>
        <ol class="list-unstyled mb-0">
          <li><a href="#">March 2014</a></li>
          <li><a href="#">February 2014</a></li>
          <li><a href="#">January 2014</a></li>
          <li><a href="#">December 2013</a></li>
          <li><a href="#">November 2013</a></li>
          <li><a href="#">October 2013</a></li>
          <li><a href="#">September 2013</a></li>
          <li><a href="#">August 2013</a></li>
          <li><a href="#">July 2013</a></li>
          <li><a href="#">June 2013</a></li>
          <li><a href="#">May 2013</a></li>
          <li><a href="#">April 2013</a></li>
        </ol>
      </div>

      <div class="p-4">
        <h4 class="font-italic">Elsewhere</h4>
        <ol class="list-unstyled">
          <li><a href="#">GitHub</a></li>
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Facebook</a></li>
        </ol>
      </div>
    </aside><!-- /.blog-sidebar -->

  </div><!-- /.row -->
</main>
{% endblock %}

travelapp/templates/travelapp/route_detail.html
{% extends 'mainsite/base.html' %}
{% block content %}
<main role="main" class="container">
  <div class="row">
    <div class="col-md-12 blog-main">
      <h3 class="pb-4 mb-4 font-italic border-bottom">Описание маршрута</h3>
        <div class="row">
            {% if object.is_active %}
              <div class="blog-post">
                <div class="row">
                <div class="route-image p-4 col-4">
                  <img src="/{{object.featured_photo}}" alt="" class="img-fluid img-thumbnail">
                </div>
                <div class="col-8">
                    <h2 class="blog-post-title"><a href="{% url 'travelapp:route_read' object.pk %}">{{ object.name }}</a></h2>
                    <p class="blog-post-meta">{{ object.added_at }} by <a href="#">{{ object.instructor.user.get_full_name }}</a></p>

                    <p>Место: {{ object.location.name }}</p>
                    <hr>
                    <p>{{ object.short_desc }}</p>
                    <hr>
                    <p>Тип: {{ object.get_type_display }}, cложность: <span class="p-0 btn
                      {% if object.complexity == 1 %}
                        btn-success
                      {% elif object.complexity == 2 %}
                        btn-warning
                      {% else %}
                        btn-danger
                      {% endif %}
                      ">{{ object.get_complexity_display }}</span></p>
                    <p>Длина: {{ object.length }}км, продолжительность (в днях): {{ object.duration }}</p>
                </div>
                </div>
                <p class="">{{ object.long_desc}}</p>
                <div class="row">
                {% for photo in object.photos.all %}
                  <div class="col-md-3">
                    <div class="route-image p-2">
                      <a href="/{{ photo.image }}">
                        <img src="/{{ photo.image }}" class="img-fluid img-thumbnail" alt="Lights">
                        <div class="caption">
                          <p>Lorem ipsum...</p>
                        </div>
                      </a>
                    </div>
                  </div>
                {% endfor %}
                </div>
                <p class="h4 my-3">Запланированные походы:</p>
                {% for trip in object.get_planned.all %}
                <div class="row justify-content-center">
                    <div class="col-2 border">{{ trip.starts_at|date:"d M Y" }} {{trip.starts_at|time:"H:i"}}</div>
                    <div class="col-4 border">{{ trip.instructor.user.get_full_name }}</div>
                    <div class="col-2 border">{{ trip.price }}</div>
                    <div class="col-1 border">{{ trip.subbed }}/{{ trip.max_group_size }}</div>
                    <a href="{% url 'ordersapp:create_order' trip.pk %}" class="btn btn-sm btn-info">Заказать</a>
                </div>
                {% empty %}
                  <p>По данному маршруту не запланировано ни одного похода.</p>
                {% endfor %}
                <p class="h4 my-3">Проведённые походы:</p>
                {% for trip in object.get_finished_trips.all %}
                <div class="row justify-content-center">
                    <div class="col-2 border">{{ trip.starts_at|date:"d M Y" }} {{trip.starts_at|time:"H:i"}}</div>
                    <div class="col-4 border">{{ trip.instructor.user.get_full_name }}</div>
                    <div class="col-2 border">{{ trip.price }}</div>
                    <div class="col-1 border">{{ trip.subbed }}/{{ trip.max_group_size }}</div>
                    <a href="{% url 'socialapp:trip_comment_create' trip.pk %}" class="btn btn-sm btn-info">Оценить</a>
                </div>
                {% empty %}
                  <p>По данному маршруту не запланировано ни одного похода.</p>
                {% endfor %}
                <p class="h4 my-3">Отзывы</p>
                {% for comment in object.get_route_comments.all %}
                <div class="row col-10 justify-content-left mx-4 border p-3">
                    <div class="row col-12 border">
                        <div class="col-1">{{ comment.score }}*</div>
                        <div class="col-3"><a href="{% url 'userapp:traveler_details' comment.author.pk %}">{{ comment.author.get_full_name }}</a></div>
                        <div class="col-3">{{comment.added_at}}</div>
                    </div>
                    <div class="row border col-12 my-3">
                        <div class="col-6">Поход проходил: {{comment.trip.starts_at|date}} — {{comment.trip.ends_at|date}}</div>
                        <div class="col-6">
                            Инструктор:
                            <a href="{% url 'userapp:traveler_details' comment.trip.instructor.user.pk %}">
                                {{comment.trip.instructor.user.get_full_name}}
                            </a>
                        </div>
                    </div>
                    <div class="row col-12 border h6 p-3">{{ comment.content }}</div>
                    <div class="row col-12">
                        {% for photo in comment.photos.all %}
                          <div class="col-md-4">
                            <div class="route-image p-2">
                              <a href="/{{ photo.image }}">
                                <img src="/{{ photo.image }}" class="img-fluid img-thumbnail" alt="Lights">
                                <div class="caption">
                                  <p>Lorem ipsum...</p>
                                </div>
                              </a>
                            </div>
                          </div>
                        {% endfor %}
                    </div>
                </div>
                {% empty %}
                  <p>К данному маршруту ещё не написано ни одного отзыва.</p>
                {% endfor %}
              </div><!-- /.blog-post -->
            {% endif %}
        </div>

<!--      <nav class="blog-pagination">-->
<!--        <a class="btn btn-outline-primary" href="#">Older</a>-->
<!--        <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Newer</a>-->
<!--      </nav>-->

    </div><!-- /.blog-main -->

  </div><!-- /.row -->
</main>
{% endblock %}

travelapp/templates/travelapp/route_list.html
{% extends 'mainsite/base.html' %}
{% block content %}
<main role="main" class="container">
  <div class="row">
    <div class="col-md-12 blog-main">
      <h3 class="pb-4 mb-4 font-italic border-bottom">Список маршрутов</h3>
        {% include 'travelapp/includes/inc-filter-form.html' %}
        <div class="row">
        {% for route in object_list %}
            {% if route.is_usable %}
              <div class="blog-post col-4 p-1">
                <div class="bg-light p-3">
                <div class="route-image p-4">
                  <img src="/{{route.featured_photo}}" alt="" class="img-fluid img-thumbnail">
                </div>
                <h2 class="blog-post-title text-center"><a href="{% url 'travelapp:route_read' route.pk %}">{{ route.name }}</a></h2>
                <p class="blog-post-meta">Инструктор: <a href="#">{{ route.instructor.user.get_full_name }}</a></p>

                <p>Место: {{ route.location.name }}</p>
                <hr>
                <p>{{ route.short_desc }}</p>
                <hr>
                <p>Тип: {{ route.get_type_display }}, cложность: <span class="p-0 btn
                  {% if route.complexity == 1 %}
                    btn-success
                  {% elif route.complexity == 2 %}
                    btn-warning
                  {% else %}
                    btn-danger
                  {% endif %}
                  ">{{ route.get_complexity_display }}</span></p>
                <p>Длина: {{ route.length }}км (займёт примерно {{ route.duration }} дней)</p>
              </div>
              </div><!-- /.blog-post -->
            {% endif %}
        {% endfor %}
        </div>

<!--      <nav class="blog-pagination">-->
<!--        <a class="btn btn-outline-primary" href="#">Older</a>-->
<!--        <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Newer</a>-->
<!--      </nav>-->

    </div><!-- /.blog-main -->

  </div><!-- /.row -->
</main>
{% endblock %}

travelapp/templates/travelapp/trip_selector.html
{% extends 'mainsite/base.html' %}
{% block content %}
<main role="main" class="container">
  <div class="row">
    <div class="col-md-12 blog-main">
      <h3 class="pb-4 mb-4 font-italic border-bottom text-center">Подбор похода</h3>
        {% include 'travelapp/includes/inc-filter-form.html' %}
        <div class="row my-4">
        {% for trip in trip_list %}
          {% if forloop.first %}
          <div class="row col-12 justify-content-center font-weight-bold">
              <div class="col-1 border">Обзор</div>
              <div class="col-2 border">Даты</div>
              <div class="col-2 border">Регион</div>
              <div class="col-2 border">Тип маршрута</div>
              <div class="col-2 border">Сложность</div>
              <div class="col-1 border">Цена</div>
              <div class="col-1 border">Занято</div>
              <div class="col-1 border">Запись</div>
          </div>
          {% endif %}
          <div class="row col-12 justify-content-center">
              <div class="col-1 border"><a href="{% url 'travelapp:route_read' trip.route.pk %}"><img class="mx-auto d-block" src="/static/img/View.svg" alt="Показать"></a></div>
              <div class="col-2 border">{{ trip.starts_at|date:"d M Y" }}<br>{{ trip.ends_at|date:"d M Y" }}</div>
              <div class="col-2 border">{{ trip.route.location }}</div>
              <div class="col-2 border">{{ trip.route.get_type_display }}</div>
              <div class="col-2 border">{{ trip.route.get_complexity_display }}</div>
              <div class="col-1 border">{{ trip.price }} </div>
              <div class="col-1 border">{{ trip.subbed }}/{{ trip.max_group_size }}</div>
              <div class="col-1 border"><a href="{% url 'ordersapp:create_order' trip.pk %}" class="btn btn-sm btn-info">Заказать</a></div>
          </div>
        {% endfor %}
        </div>
        <h4 class="pb-4 mb-4 font-italic border-bottom text-center">Популярные маршруты</h4>
        <div class="row">
        {% for route in route_list %}
            {% if route.is_usable %}
              <div class="blog-post col-4 p-1">
                <div class="bg-light p-3">
                <div class="route-image p-4">
                  <img src="/{{route.featured_photo}}" alt="" class="img-fluid img-thumbnail">
                </div>
                <h2 class="blog-post-title text-center"><a href="{% url 'travelapp:route_read' route.pk %}">{{ route.name }}</a></h2>
                <p class="blog-post-meta">Инструктор: <a href="#">{{ route.instructor.user.get_full_name }}</a></p>

                <p>Место: {{ route.location.name }}</p>
                <hr>
                <p>{{ route.short_desc }}</p>
                <hr>
                <p>Тип: {{ route.get_type_display }}, cложность: <span class="p-0 btn
                  {% if route.complexity == 1 %}
                    btn-success
                  {% elif route.complexity == 2 %}
                    btn-warning
                  {% else %}
                    btn-danger
                  {% endif %}
                  ">{{ route.get_complexity_display }}</span></p>
                <p>Длина: {{ route.length }}км (займёт примерно {{ route.duration }} дней)</p>
              </div>
              </div><!-- /.blog-post -->
            {% endif %}
        {% endfor %}
        </div>

<!--      <nav class="blog-pagination">-->
<!--        <a class="btn btn-outline-primary" href="#">Older</a>-->
<!--        <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Newer</a>-->
<!--      </nav>-->

    </div><!-- /.blog-main -->

  </div><!-- /.row -->
</main>
{% endblock %}